baseURL                          = "https://uma1100.github.io/uma/"  # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "ja"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics
canonifyurls = true

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/favicon.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "yumayuma0322@gmail.com"   # E-mail address for contact section
    customCSS                    = "/foo.css"             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Japan"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three
    [params.gallery]
        useTwoColumns            = false                   # Use a layout with two columns instead of three


    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    #[[params.social]]
    #   url   = "https://twitter.com/mozzz111010"
    #  icon  = "twitter" # icon name without the 'fa-'
    #    icon_pack = "fab"
    [[params.social]]
        url   = "https://www.facebook.com/profile.php?id=100005573319406"
        icon  = "facebook-f" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/in/yuma-itonaga-56633b175/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.instagram.com/m0z_zz/"
        icon  = "instagram" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "mailto:yumayuma0322@gmail.com"
        icon  = "envelope" # icon name without the 'fa-'
        icon_pack = "fas"
    

# If you don't want to use the default menu, you can define one by yourself
[[menu.main]]
    name    = "Home"
    url     = "/"
    weight  = 1
[[menu.main]]
    name    = "About"
    url     = "/about"
    weight  = 2
[[menu.main]]
    name    = "Project"
    url     = "/projects/"
    weight  = 3
[[menu.main]]
    name    = "Gallery"
    url     = "/gallery/"
    weight  = 4
[[menu.main]]
    name    = "Blog"
    url     = "/blog/"
    weight  = 5
#[[menu.main]]
#    name    = "Contact"
#    url     = "/#contact"
#    weight  = 6

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    #[languages.en]
     #   languageName     = "English"
      #  languageCode     = "en-us"
       # contentDir       = "content/en"
      #  weight           = 0
      #  title            = "Introduction"
       # [languages.en.params]
       #     description  = "Website Description"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)
    [languages.ja]
        languageName     = "Japanese"
        languageCode     = "ja"
        contentDir       = "content/ja"
        weight           = 0
        title            = "Itonaga"
        [languages.ja.params]
            description  = "this is Itonaga(mozzz) HP"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)


